[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ogc_reserve = "42b3W6c34GqwoxUgkrV4hdG9EiCWvLicHQ6iTKk7eWHs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
